version: 2
jobs:
  deploy-develop:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2e:06:04:80:fd:e7:e2:a2:96:67:eb:8f:ed:15:35:95"
      - run:
          name: Setup SSH Key Host
          command: |
            ssh-keyscan -H $SSH_HOST_DEVELOP >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            ssh $SSH_USER@$SSH_HOST_DEVELOP "cd zoobc-explorer-ui/
            chmod +x deploy.sh
            ./deploy.sh"

workflows:
  version: 2
  build:
    jobs:
      - deploy-develop:
          filters:
            branches:
              only: develop

