version: 2
jobs:
  deploy-develop:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "eb:47:ac:d7:d7:d2:ff:5a:5a:26:24:54:b4:cf:6d:69"
      - run:
          name: Setup SSH Key Host
          command: |
            ssh-keyscan -H ${SSH_HOST_DEVELOP} >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            ssh ${SSH_USER}@${SSH_HOST_DEVELOP} "cd zoobc-explorer-ui/ && ./deploy.sh"

workflows:
  version: 2
  build:
    jobs:
      - deploy-develop:
          filters:
            branches:
              only: develop

