version: 2
jobs:
  deploy-develop:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - '37:8d:8b:24:af:82:09:06:2e:c4:30:d3:15:6b:ef:8d'
      - run:
          name: Setup SSH Key Host
          command: |
            ssh-keyscan -H ${SSH_HOST_DEVELOP} >> ~/.ssh/known_hosts
      - run:
          name: Deploy Develop
          command: |
            ssh ${SSH_USER}@${SSH_HOST_DEVELOP} "cd zoobc-explorer-ui/ && ./deploy.sh"

workflows:
  version: 2
  build:
    jobs:
      - deploy-develop:
          filters:
            branches:
              only: develop
